### ISSUE TITLE
Red screen on launch

### ISSUE THREAD

**Issue by z3rods** [ihaveamac/mashers-gl-updater#2]
Whenever I start the updater, it starts but then stops at the red screen every time. It will remain on said screen until the 3DS is rebooted with the L+R+B+Down combo or until it is turned off.
The files (the .3dsx, icon, and lua index files themselves) for the updater are located in 'gridlauncher/update'. I'm on a N3DS running the latest firmware with the *hax 2.5 payload. Linked below is a short video showing what happens when I launch the updater.

https://www.youtube.com/watch?v=xzl0oXxhrJk

EDIT: I also should mention that I'm on Beta 113 of Mashers's Launcher.

**Comment by ihaveamac** [comment]
did you properly replace the .3dsx? if you're using FTP, you may want to delete it first then upload it.

**Comment by z3rods** [comment]
This was actually the first I had ever put it in the update folder. Until
this morning, I was still using 1.23 because I was unaware that the updater
had been updated.

**Comment by ihaveamac** [comment]
well this seems like an issue with "mglupdate.3dsx". try extracting the latest release to its own folder like /3ds/mglupdate then run it. it should replace itself at the proper location.

**Comment by z3rods** [comment]
Well that seems to have worked. Cheers! :+1:
