### ISSUE TITLE
changelog support

### ISSUE THREAD

**Issue by ihaveamac** [ihaveamac/mashers-gl-updater#3]
- using two files:
  - [Updating-Changelog-Beta.md](https://github.com/RedInquisitive/3DS-Homebrew-Menu-Wiki/blob/master/Updating/Updating-Changelog-Beta.md)
  - [Updating-Changelog.md](https://github.com/RedInquisitive/3DS-Homebrew-Menu-Wiki/blob/master/Updating/Updating-Changelog.md) (for release)
- DPad Left/Right changes beta versions
- DPad Up/Down scrolls (if necessary) by changing starting line number
- show the changelog for the version directly after the user's installed one (i.e. if user has 110, display 111)
- might require a rewrite of how menus are displayed (which would easily enable adding other options)

**Comment by mashers** [comment]
Just another thought about this, at some point this will no longer be in beta. It might be worth bearing this in mind when you write your code to parse the markdown file.

**Comment by ihaveamac** [comment]
but exactly when would that be? pushing a change to look for "`## Release`" as well wouldn't be too difficult.

you could also, once it's no longer out of beta, rename the page to `Updating-Changelog-Beta.md` and put all the release ones to the current filename.

**Comment by ihaveamac** [comment]
alternatively you could move it to `-Beta` right now, to retain compatibility with older versions of the updater which people might still have for some time.

**Comment by mashers** [comment]
Great ideas! Ok, I think what we need is the following:
1. Rename Updating-Changelog.md to Updating-Changelog-Beta.md
2. Create Updating-Changelog-Release.md as a placeholder (I won't add a sidebar link in the wiki, and I'll just put a coming soon message for now in case somebody finds it)
3. The beta changelog will continue to use "## Beta xxx" as the version number
4. The release changelog will, eventually, use "## Release xxx" as the version number

This way you can account for this formatting when updating the updater. The only issue now is how will the updater know whether the latest update is a beta or a release? In other words, how will it know which markdown file to look at? Perhaps a flag in the PHP script could be set to show that the launcher is still in beta, and cause the beta md to be used, and when we need to switch to using the release md this flag could be removed (or set to false) so the release changelog would be used.

If that all sounds ok then I'll make the changes to the wiki now.

**Comment by ihaveamac** [comment]
> The only issue now is how will the updater know whether the latest update is a beta or a release?

I'm going to look at this one separately. maybe a change to version.h is needed? inside the launcher itself, it doesn't do much other than display a number.

maybe you could change it to something like `#define currentversion "b129"` if possible, and for releases just drop the b (or change it to r, or v, or whatever, just tell me). I would need to make a quick change to the updater so it would remove the quotes from 'The latest version is "b129".'

> In other words, how will it know which markdown file to look at?

look above!

if it's a beta then it would look for `-Beta`. if it's a release then it would look for `-Release`.

**Comment by mashers** [comment]
Ok, I'll change version.h to define the version as a string and include a 'b' at the beginning of the version. That way you can check for the presence of a b in the version number check in order to establish whether or not the version number refers to a beta.

**Comment by ihaveamac** [comment]
make sure that it works and displays the version in the launcher properly! I don't want to work on top of something that might break and be changed.

**Comment by ihaveamac** [comment]
be sure to also check how the current updater (2.1) interprets the locally installed version.

**Comment by mashers** [comment]
Ok, I've just changed it to a string with 'b' at the beginning. It displays correctly in the launcher, and Updater 2.1 correctly states "Installed: b128" at the top :)

**Comment by ihaveamac** [comment]
which one does it say?
- Installed: "b128"
- Installed: b128

and
- The latest version is "b128".
- The latest version is b128.

**Comment by mashers** [comment]
It says:

**Installed: b128**

I haven't pushed this update yet as I'm working on something else as well, so I don't yet know how it will format the latest version string. I'll check this and let you know in a little while.

**Comment by ihaveamac** [comment]
can you quickly post the contents of your local `version.h`?

**Comment by mashers** [comment]
Sure:

```
#define currentversion "b128"
```

**Comment by ihaveamac** [comment]
oh wait, I got an idea. the launcher isn't putting the quotes in `glinfo.txt` but they would appear in the updater since they would exist in `version.h`. I got this now I think.

**Comment by mashers** [comment]
That's right, it's logging the value of the string, hence there are no quotes. By the way, I've just updated the wiki so it contains two separate markdown files for the changelog:
- Updating-Changelog-Beta.md - currently linked from the sidebar
- Updating-Changelog.md - not currently linked from the sidebar, it's just there as a placeholder for when the launcher comes out of beta

**Comment by ihaveamac** [comment]
I thought it was going to be `-Release`. changed your mind? both are fine, by the way.

**Comment by mashers** [comment]
I think I prefer to leave it without -Release, as the beta changelog will be there as a legacy so it doesn't need to be differentiated to that extent if that makes sense.

**Comment by mashers** [comment]
I'm ready to push an update which will include the new version string formatted with the leading 'b'. Is this ok?

**Comment by ihaveamac** [comment]
it should work. the quotes around the version should only be cosmetic and I'll include it in another update.

**Comment by mashers** [comment]
Ok! Here goes :)

**Comment by mashers** [comment]
Done. New update is now on GH and version.h has been updated. The updater now shows the following:

**The latest version is "b129"**

**Comment by mashers** [comment]
Oh, and while downloading it says

**Downloading "b129", be patient!**

**Comment by mashers** [comment]
But it does work ;)

**Comment by ihaveamac** [comment]
that's fine. I will probably add very basic changelog support in a 2.2 or something (only showing the latest version and stuff), and then redo all of it for a 3.0.

**Comment by mashers** [comment]
No worries - well the behind-the-scenes stuff is set up for now, so hopefully it's all ready for you whenever you want to start working on this :)

**Comment by ihaveamac** [comment]
still not satisfactory but good enough for the time being.
